### ISSUE TITLE
Missing hover effect for menu items

### ISSUE THREAD

**Issue by jaumecapdevila** [nickcernis/blackbird-jetbrains#1]
Hi @nickcernis, first of all, thanks for this awesome theme. I've recently started using it and so far I like it. The only issue I've found is that in some menus, (for example the menu to create new files or directories), there is no focus/hover effect to the menu items which makes it hard to know which item you have selected. If you do not have the time to fix it, you can indicate me how to do it as I've never worked on a Jetbrains theme before.

<img width="376" alt="Screenshot 2020-10-20 at 10 58 37" src="https://user-images.githubusercontent.com/7687573/96564742-d700ab00-12c3-11eb-8bea-ee390b0ee229.png">

Check the attached screenshot.

**Comment by jaumecapdevila** [comment]
It also happens in other menus:

![Uploading Screenshot 2020-10-20 at 11.05.10.png…]()

**Comment by jaumecapdevila** [comment]
It also happens in other menus:
 
<img width="280" alt="Screenshot 2020-10-20 at 11 05 10" src="https://user-images.githubusercontent.com/7687573/96565140-45de0400-12c4-11eb-8792-094dfbce4e34.png">

**Comment by nickcernis** [comment]
Thanks for the kind words and the report, @jaumecapdevila. I'll take a look.

**Comment by nickcernis** [comment]
@jaumecapdevila I submitted version 0.2.1 to JetBrains with a fix for this. It should be reviewed and available within 48 hours, but usually sooner.

**Comment by jaumecapdevila** [comment]
Awesome, thanks for your time @nickcernis 😄

**Comment by nickcernis** [comment]
0.2.1 is out now.
